Create Readme file
coopengo/coog-bench pull request #11
Opened 2017-03-06 13:48 UTC by FloraMau

Offers information about architecture and usage of the module coog-bench.

2017-03-06 16:24 UTC, JCavallo requested changes
Style : 80 colonnes

2017-03-06 16:24 UTC, JCavallo commented on README.md
> +- The graphic chart of Coopengo is respected.
Ca n'a probablement pas sa place dans un module public

2017-03-06 16:25 UTC, FloraMau commented on README.md
> +- The graphic chart of Coopengo is respected.
ok

2017-03-06 17:05 UTC, JCavallo commented on README.md
> +Backbone.js is a lightweight JavaScript library that gives structure to web
En général on rends le lien clickable vers le site / dépôt

2017-03-06 17:05 UTC, JCavallo commented on README.md
> +![alt tag](png/schema2.png "Functioning of a plugin")
Functioning => Behavior

2017-03-06 17:07 UTC, FloraMau commented on README.md
> +Backbone.js is a lightweight JavaScript library that gives structure to web
Je l'ai mis après en fait le lien vers le site de Backbone

2017-03-06 17:12 UTC, JCavallo commented on README.md
> +Backbone.js is a lightweight JavaScript library that gives structure to web
J'ai vu, mais mettre un lien clickable c'est quand même mieux...

Sinon, tu fais référence aux fichiers COPYRIGHT / LICENSE, mais je ne les vois pas :'(

2017-03-07 08:48 UTC, FloraMau commented on README.md
> +Backbone.js is a lightweight JavaScript library that gives structure to web
done :)

2017-03-07 08:55 UTC, JCavallo approved these changes

2017-03-07 09:01 UTC, merged