Review UX
coopengo/coog-bench pull request #7
Opened 2017-02-28 14:26 UTC by FloraMau

Use bootstrap, responsive and clean design.
Graphical bug resolved.

2017-03-02 09:49 UTC, alikefia requested changes

2017-03-02 09:49 UTC, alikefia commented on public/css/stylesheet.css
> +   font-family: 'myFirstFont';
Name??

2017-03-02 09:49 UTC, alikefia commented on public/index.html
> +  <link rel="stylesheet" href="bootstrap.min.css" />
Toutes les ressources css doivent être dans coog-bench.css (require dans le code)
D'ailleurs la lib ne doit pas être sous git

2017-03-02 09:49 UTC, alikefia commented on public/index.html
> +  <link rel="stylesheet" href="css/stylesheet.css"/>
idem: un seul fichier concaténé: nos sources doivent être sous src

2017-03-02 09:49 UTC, alikefia commented on public/index.html
> +  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
idem (btw, it is already there)

2017-03-02 09:49 UTC, alikefia commented on src/bench/drop.js
> +    this.destroy();
Why?

2017-03-02 09:49 UTC, alikefia commented on src/bench/model.js
> +      status: 'bench-body',
pardon?

2017-03-02 09:49 UTC, alikefia commented on src/bench/template/drop.css
>  #buttondrop {
bench-button-drop

2017-03-02 09:49 UTC, alikefia commented on src/bench/template/drop.css
> +  border: 2px solid #46423d;
Pq autant de spécifique? les defaults de bootstrap ne répondent pas?

2017-03-02 09:49 UTC, alikefia commented on src/bench/template/drop.tpl
> +	</div>
C'est pas le truc qu'on doit placer en haut mnt?

2017-03-02 09:49 UTC, alikefia commented on src/bench/template/row.css
> +#btngo {
bench-button-go

2017-03-02 09:49 UTC, alikefia commented on src/bench/template/row.css
> +  border-radius: 0px;
pareil, on ne va pas spécifier chaque bouton

2017-03-02 09:49 UTC, alikefia commented on src/bench/template/table.tpl
> +<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 col-lg-offset-5 col-md-offset-5 col-sm-offset-5">
C'est pas aligné

2017-03-02 09:49 UTC, alikefia commented on src/session/logout.tpl
> +<div class="row"></br></div>
c pas dans session, ça ne doit pas s'appeler logout

2017-03-02 10:11 UTC, FloraMau commented on src/bench/drop.js
> +    this.destroy();
Le bouton disparait quand on clique dessus

2017-03-02 15:32 UTC, FloraMau commented on src/bench/model.js
> +      status: 'bench-body',
corrected

2017-03-02 15:34 UTC, FloraMau commented on src/bench/template/drop.css
>  #buttondrop {
corrected

2017-03-03 10:05 UTC, FloraMau commented on src/bench/template/row.css
> +#btngo {
corrected

2017-03-03 10:07 UTC, FloraMau commented on src/bench/template/table.tpl
> +<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 col-lg-offset-5 col-md-offset-5 col-sm-offset-5">
done

2017-03-03 10:07 UTC, FloraMau commented on src/session/logout.tpl
> +<div class="row"></br></div>
corrected

2017-03-15 16:51 UTC, alikefia approved these changes

2017-03-15 16:51 UTC, merged